### ISSUE TITLE
不要なディレクトリがcommitされています

### ISSUE THREAD

**Issue by helloooooo** [kimunet/RailsTutorials#1]
.DSstoreやvendor以下のファイルはコミットされてないようにしましょう
.gitignoreを編集してみてください

**Comment by kimunet** [comment]
ありがとうございます。対応完了しました。(2019/06/25 22:36)

変更内容
.gitignore を編集し、
.DS_Store
/vendor
を追記。
gitのcashを削除してから、pushして反映

**Comment by kimunet** [comment]
Issueをクローズします。
